# aes67-daemon configuration
# Based on git@github.com:bondagit/aes67-linux-daemon.git
[ptp]
domain=0
interface=eth0
# Grandmaster priority
priority1=128
priority2=128

[rtp]
mcast_prefix=239.69.0.0
sample_rate=48000
packet_time=1.0 # 1ms / 48 samples
bit_depth=24
